const SUPABASE_URL='https://pmcxxstouaqpyfnfpcoo.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_jpQqkPqtD-oCXHtoK2ppng_41JYTa-L';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const loginWrap=document.getElementById('loginWrap'),app=document.getElementById('app'),loginForm=document.getElementById('loginForm'),loginError=document.getElementById('loginError'),list=document.getElementById('list'),messages=document.getElementById('messages'),player=document.getElementById('player'),form=document.getElementById('form'),input=document.getElementById('input'),toggleStatus=document.getElementById('toggleStatus'),search=document.getElementById('search'),adminMeta=document.getElementById('adminMeta'),adminAlias=document.getElementById('adminAlias'),adminNote=document.getElementById('adminNote'),saveMeta=document.getElementById('saveMeta'),metaStatus=document.getElementById('metaStatus');
const adminImageInput=document.getElementById('adminImageInput'),adminImagePick=document.getElementById('adminImagePick'),adminImagePreview=document.getElementById('adminImagePreview');
const soundToggle=document.getElementById('soundToggle'),openChatSearch=document.getElementById('openChatSearch'),chatSearch=document.getElementById('chatSearch'),chatSearchInput=document.getElementById('chatSearchInput'),chatSearchCount=document.getElementById('chatSearchCount'),chatSearchPrev=document.getElementById('chatSearchPrev'),chatSearchNext=document.getElementById('chatSearchNext'),chatSearchClose=document.getElementById('chatSearchClose');
let conversations=[],current=null,currentMessages=[],filter='all',channel=null,searchHits=[],searchPos=-1,adminSelectedImages=[];
const imageUrlCache=new Map();
let unread=JSON.parse(localStorage.getItem('syndfco_admin_unread')||'{}');
let soundOn=localStorage.getItem('syndfco_admin_sound')!=='off';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=v=>{const d=new Date(v);return `${d.toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})} ${String(d.getDate()).padStart(2,'0')}-${String(d.getMonth()+1).padStart(2,'0')}`};
const saveUnread=()=>localStorage.setItem('syndfco_admin_unread',JSON.stringify(unread));
function updateSoundButton(){soundToggle.textContent=soundOn?'🔔 Âm: Bật':'🔕 Âm: Tắt';soundToggle.classList.toggle('off',!soundOn)}
function playNotification(){if(!soundOn)return;try{const A=window.AudioContext||window.webkitAudioContext,ctx=new A(),o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(740,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(980,ctx.currentTime+.12);g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.10,ctx.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.22);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.23)}catch(e){}}
soundToggle.onclick=()=>{soundOn=!soundOn;localStorage.setItem('syndfco_admin_sound',soundOn?'on':'off');updateSoundButton();if(soundOn)playNotification()};updateSoundButton();
async function isAdmin(){const {data,error}=await db.rpc('is_admin');return !error&&data===true}
async function showApp(){if(!(await isAdmin())){await db.auth.signOut();loginError.textContent='Tài khoản này chưa được cấp quyền Admin.';return}loginWrap.classList.add('hidden');app.classList.add('open');await loadConversations();subscribe()}
loginForm.onsubmit=async e=>{e.preventDefault();loginError.textContent='Đang đăng nhập...';const {error}=await db.auth.signInWithPassword({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value});if(error){loginError.textContent='Sai email hoặc mật khẩu.';return}loginError.textContent='';await showApp()};
document.getElementById('logout').onclick=async()=>{await db.auth.signOut();location.reload()};
async function loadConversations(){const {data,error}=await db.from('conversations').select('*').order('updated_at',{ascending:false});if(error){console.error(error);list.innerHTML='<div class="empty">Không tải được inbox.</div>';return}conversations=(data||[]).sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at));if(current)current=conversations.find(c=>c.id===current.id)||current;renderList()}
function renderList(){const q=search.value.trim().toLowerCase();const rows=conversations.filter(c=>(filter==='all'||c.status===filter)&&(!q||`${c.player_name} ${c.player_id} ${c.zalo} ${c.server} ${c.admin_alias||''} ${c.admin_note||''}`.toLowerCase().includes(q)));list.innerHTML=rows.length?rows.map(c=>{const n=Number(unread[c.id]||0);return `<button class="item ${current?.id===c.id?'active':''} ${n?'has-unread':''}" data-id="${c.id}"><span class="badge ${c.status}">${c.status==='closed'?'Đã xử lý':'Đang hỗ trợ'}</span><b>${esc(c.admin_alias||c.player_name)}</b>${c.admin_alias?`<span class="real-name">Nhân vật: ${esc(c.player_name)}</span>`:''}<span>ID: ${esc(c.player_id)}</span><small>${esc(c.server)} • Zalo: ${esc(c.zalo)}</small>${c.admin_note?`<small class="note-preview">📝 ${esc(c.admin_note)}</small>`:''}${n?`<span class="unread-badge">${n>99?'99+':n}</span>`:''}</button>`}).join(''):'<div class="empty">Không có cuộc trò chuyện.</div>';list.querySelectorAll('.item').forEach(b=>b.onclick=()=>selectConversation(b.dataset.id))}
async function getImageUrl(path){if(!path)return '';if(imageUrlCache.has(path))return imageUrlCache.get(path);const {data,error}=await db.storage.from('support-images').createSignedUrl(path,3600);if(error){console.error(error);return ''}imageUrlCache.set(path,data.signedUrl);return data.signedUrl}
async function hydrateImages(root=messages){for(const img of root.querySelectorAll('img[data-image-path]')){const url=await getImageUrl(img.dataset.imagePath);if(url)img.src=url}}
function clearAdminImage(){adminSelectedImages=[];adminImageInput.value='';adminImagePreview.classList.add('hidden');adminImagePreview.innerHTML=''}
function showAdminImages(files){adminImagePreview.innerHTML=`<div class="preview-grid">${files.map((file,i)=>`<div class="preview-thumb"><img src="${URL.createObjectURL(file)}" alt="Ảnh ${i+1}"><button type="button" data-remove-image="${i}">×</button></div>`).join('')}</div><span>${files.length} ảnh đã chọn</span><button type="button" id="removeAdminImage">Xóa hết</button>`;adminImagePreview.classList.remove('hidden');adminImagePreview.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{adminSelectedImages.splice(Number(b.dataset.removeImage),1);adminImageInput.value='';adminSelectedImages.length?showAdminImages(adminSelectedImages):clearAdminImage()});document.getElementById('removeAdminImage').onclick=clearAdminImage}
function imagePaths(value){if(!value)return[];try{const a=JSON.parse(value);if(Array.isArray(a))return a.filter(Boolean)}catch(e){}return [value]}
function imageGridHtml(value){const paths=imagePaths(value);if(!paths.length)return'';return `<div class="chat-image-grid count-${paths.length}">${paths.map(p=>`<img class="chat-image" data-image-path="${esc(p)}" alt="Ảnh gửi trong chat">`).join('')}</div>`}
async function uploadChatImage(file,conversationId){const {data:{user}}=await db.auth.getUser();const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${user.id}/${conversationId}/${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('support-images').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path}
async function selectConversation(id){current=conversations.find(c=>c.id===id);delete unread[id];saveUnread();renderList();closeMessageSearch();if(!current)return;player.innerHTML=`<div><b>${esc(current.admin_alias||current.player_name)}</b>${current.admin_alias?` <span class="player-real">(${esc(current.player_name)})</span>`:''} • ID: ${esc(current.player_id)} • ${esc(current.server)} • Zalo: ${esc(current.zalo)}</div>`;adminMeta.classList.remove('hidden');adminAlias.value=current.admin_alias||'';adminNote.value=current.admin_note||'';metaStatus.textContent='';input.disabled=false;form.querySelector('.send-btn').disabled=false;toggleStatus.disabled=false;openChatSearch.disabled=false;adminImagePick.disabled=false;clearAdminImage();toggleStatus.textContent=current.status==='closed'?'Mở lại hỗ trợ':'Đánh dấu đã xử lý';const {data,error}=await db.from('messages').select('*').eq('conversation_id',id).order('created_at',{ascending:true});if(error)return;currentMessages=data||[];renderMessages()}
function renderMessages(){messages.innerHTML=currentMessages.map(m=>`<div class="msg ${m.sender}" data-message-id="${m.id}">${imageGridHtml(m.image_path)}<span class="msg-content">${m.content==='[Hình ảnh]'?'':esc(m.content)}</span><small>${m.sender==='admin'?'Support':'Bạn'} • ${time(m.created_at)}</small></div>`).join('');hydrateImages();messages.scrollTop=messages.scrollHeight;if(!chatSearch.classList.contains('hidden'))runMessageSearch(false)}
adminImagePick.onclick=()=>adminImageInput.click();adminImageInput.onchange=()=>{const files=[...adminImageInput.files].slice(0,3);if(!files.length)return;if(adminImageInput.files.length>3)alert('Mỗi lần gửi tối đa 3 ảnh.');if(files.some(file=>!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)){alert('Mỗi ảnh chỉ nhận JPG, PNG, WebP tối đa 5MB.');clearAdminImage();return}adminSelectedImages=files;showAdminImages(files);form.querySelector('.send-btn').disabled=false};
form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();const files=[...adminSelectedImages];if((!text&&!files.length)||!current)return;input.value='';form.querySelector('.send-btn').disabled=true;try{const paths=[];for(const file of files)paths.push(await uploadChatImage(file,current.id));const image_path=paths.length?(paths.length===1?paths[0]:JSON.stringify(paths)):null;const {error}=await db.from('messages').insert({conversation_id:current.id,sender:'admin',content:text||'[Hình ảnh]',image_path});if(error)throw error;clearAdminImage()}catch(error){console.error(error);alert('Không gửi được tin nhắn/ảnh.');input.value=text}finally{form.querySelector('.send-btn').disabled=false}}
saveMeta.onclick=async()=>{if(!current)return;const admin_alias=adminAlias.value.trim()||null,admin_note=adminNote.value.trim()||null;saveMeta.disabled=true;metaStatus.textContent='Đang lưu...';const {error}=await db.from('conversations').update({admin_alias,admin_note}).eq('id',current.id);saveMeta.disabled=false;if(error){console.error(error);metaStatus.textContent='Không lưu được.';return}current.admin_alias=admin_alias;current.admin_note=admin_note;metaStatus.textContent='Đã lưu';player.innerHTML=`<div><b>${esc(current.admin_alias||current.player_name)}</b>${current.admin_alias?` <span class="player-real">(${esc(current.player_name)})</span>`:''} • ID: ${esc(current.player_id)} • ${esc(current.server)} • Zalo: ${esc(current.zalo)}</div>`;renderList();setTimeout(()=>{if(metaStatus.textContent==='Đã lưu')metaStatus.textContent=''},1500)};
adminAlias.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();saveMeta.click()}});adminNote.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();saveMeta.click()}});
toggleStatus.onclick=async()=>{if(!current)return;const status=current.status==='closed'?'open':'closed';const {error}=await db.from('conversations').update({status}).eq('id',current.id);if(error)return alert('Không đổi được trạng thái.');current.status=status;toggleStatus.textContent=status==='closed'?'Mở lại hỗ trợ':'Đánh dấu đã xử lý';await loadConversations()};
document.getElementById('refresh').onclick=loadConversations;search.oninput=renderList;document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderList()});
function subscribe(){if(channel)db.removeChannel(channel);channel=db.channel('admin-support').on('postgres_changes',{event:'*',schema:'public',table:'conversations'},async()=>loadConversations()).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},async p=>{const isCurrent=current&&String(p.new.conversation_id)===String(current.id);if(p.new.sender!=='admin'){if(!isCurrent){unread[p.new.conversation_id]=Number(unread[p.new.conversation_id]||0)+1;saveUnread()}playNotification()}if(isCurrent&&!currentMessages.some(x=>x.id===p.new.id)){currentMessages.push(p.new);renderMessages()}await loadConversations()}).subscribe()}

function openMessageSearch(){if(!current)return;chatSearch.classList.remove('hidden');chatSearchInput.focus();runMessageSearch(false)}
function closeMessageSearch(){chatSearch.classList.add('hidden');chatSearchInput.value='';searchHits=[];searchPos=-1;chatSearchCount.textContent='0 / 0';messages.querySelectorAll('.msg').forEach(el=>{el.classList.remove('search-hit','search-current');const id=el.dataset.messageId,m=currentMessages.find(x=>String(x.id)===String(id));if(m)el.querySelector('.msg-content').innerHTML=esc(m.content)})}
function runMessageSearch(jump=true){const q=chatSearchInput.value.trim();searchHits=[];searchPos=-1;messages.querySelectorAll('.msg').forEach((el,i)=>{el.classList.remove('search-hit','search-current');const m=currentMessages[i];const content=String(m?.content||'');el.querySelector('.msg-content').innerHTML=esc(content);if(q&&content.toLocaleLowerCase('vi').includes(q.toLocaleLowerCase('vi'))){searchHits.push(el);el.classList.add('search-hit');const safe=esc(content),needle=esc(q).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');try{el.querySelector('.msg-content').innerHTML=safe.replace(new RegExp(`(${needle})`,'gi'),'<mark>$1</mark>')}catch(e){}}});if(searchHits.length){searchPos=0;setCurrentHit(jump)}else chatSearchCount.textContent='0 / 0'}
function setCurrentHit(scroll=true){searchHits.forEach(x=>x.classList.remove('search-current'));if(!searchHits.length){chatSearchCount.textContent='0 / 0';return}searchPos=(searchPos+searchHits.length)%searchHits.length;const el=searchHits[searchPos];el.classList.add('search-current');chatSearchCount.textContent=`${searchPos+1} / ${searchHits.length}`;if(scroll)el.scrollIntoView({behavior:'smooth',block:'center'})}
openChatSearch.onclick=openMessageSearch;chatSearchClose.onclick=closeMessageSearch;chatSearchInput.oninput=()=>runMessageSearch(true);chatSearchNext.onclick=()=>{if(searchHits.length){searchPos++;setCurrentHit()}};chatSearchPrev.onclick=()=>{if(searchHits.length){searchPos--;setCurrentHit()}};chatSearchInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();if(searchHits.length){searchPos+=e.shiftKey?-1:1;setCurrentHit()}}else if(e.key==='Escape')closeMessageSearch()});
(async()=>{const {data:{session}}=await db.auth.getSession();if(session)await showApp()})();


// Image lightbox
function openImageLightbox(src){if(!src)return;let box=document.getElementById('imageLightbox');if(!box){box=document.createElement('div');box.id='imageLightbox';box.className='image-lightbox';box.innerHTML='<button type="button" class="image-lightbox-close" aria-label="Đóng">×</button><img alt="Ảnh trong cuộc trò chuyện">';document.body.appendChild(box);box.addEventListener('click',e=>{if(e.target===box||e.target.classList.contains('image-lightbox-close'))box.classList.remove('open')})}box.querySelector('img').src=src;box.classList.add('open')}
messages.addEventListener('click',e=>{const img=e.target.closest('.chat-image');if(img&&img.src)openImageLightbox(img.src)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('imageLightbox')?.classList.remove('open')});
